import { ServiceDefinition } from '../types';

export const TARGET_ENDPOINTS: ServiceDefinition[] = [
  // ✅ ÇALIŞAN SERVİSLER (Test Edildi)

  // --- GİYİM & EV EŞYASI ---
  {
    id: 'kahve_dunyasi',
    name: 'Kahve Dünyası',
    url: 'https://api.kahvedunyasi.com/api/v1/auth/account/register/phone-number',
    method: 'POST',
    payloadInfo: '{"countryCode": "90", "phoneNumber": "5343622375"}',
    status: 'working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'wmf',
    name: 'WMF',
    url: 'https://www.wmf.com.tr/users/register/',
    method: 'POST',
    payloadInfo: 'Form: phone=05343622375, first_name, last_name, email, password, date_of_birth',
    status: 'working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'evidea',
    name: 'Evidea',
    url: 'https://www.evidea.com/users/register/',
    method: 'POST',
    payloadInfo: 'Multipart: phone, first_name, last_name, email, password',
    status: 'working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'dr',
    name: 'D&R',
    url: 'https://www.dr.com.tr/api/member/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5343622375"}',
    status: 'working',
    category: 'Giyim & Ev Eşyası',
  },

  // --- MARKET ---
  {
    id: 'file_market',
    name: 'File Market',
    url: 'https://api.filemarket.com.tr/v1/otp/send',
    method: 'POST',
    payloadInfo: '{"mobilePhoneNumber": "905343622375"}',
    status: 'working',
    category: 'Market',
  },

  // --- DİJİTAL HİZMETLER ---
  {
    id: 'yapp',
    name: 'Yapp',
    url: 'https://yapp.com.tr/api/mobile/v1/register',
    method: 'POST',
    payloadInfo: '{"phone_number": "5343622375", "email", "firstname", "lastname"}',
    status: 'working',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'suiste',
    name: 'Suiste',
    url: 'https://suiste.com/api/auth/code',
    method: 'POST',
    payloadInfo: '{"gsm": "5343622375", "action": "register"}',
    status: 'working',
    category: 'Dijital Hizmetler',
  },

  // --- BELEDİYE ---
  {
    id: 'fatih_belediye',
    name: 'Fatih Belediye',
    url: 'https://ebelediye.fatih.bel.tr/Sicil/KisiUyelikKaydet',
    method: 'POST',
    payloadInfo: 'Multipart: SahisUyelik.CepTelefonu, TC, Ad, Soyad, EPosta, Sifre',
    status: 'working',
    category: 'Belediye',
  },

  // --- FİNANS ---
  {
    id: 'bkm_express',
    name: 'BKM Express',
    url: 'https://www.bkmexpress.com.tr/api/v1/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "905343622375"}',
    status: 'working',
    category: 'Finans',
  },
  {
    id: 'shopandfly',
    name: 'Shop&Fly',
    url: 'https://www.shopandfly.com.tr/api/v1/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "905343622375"}',
    status: 'working',
    category: 'Finans',
  },
  {
    id: 'teb',
    name: 'TEB',
    url: 'https://www.teb.com.tr/api/v1/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "905343622375"}',
    status: 'working',
    category: 'Finans',
  },

  // ⚠️ LİMİTLİ SERVİSLER
  {
    id: 'hayat_su',
    name: 'Hayat Su',
    url: 'https://api.hayatsu.com.tr/api/SignUp/SendOtp',
    method: 'POST',
    payloadInfo: '{"mobilePhoneNumber": "5343622375", "actionType": "register"}',
    status: 'limited',
    category: 'Market',
  },
  {
    id: 'qumpara',
    name: 'Qumpara',
    url: 'https://tr-api.fisicek.com/v1.3/auth/getOTP',
    method: 'POST',
    payloadInfo: '{"msisdn": "+905343622375"}',
    status: 'limited',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'beefull',
    name: 'Beefull',
    url: 'https://app.beefull.io/api/inavitas-access-management/sms-login',
    method: 'POST',
    payloadInfo: '{"phoneCode": "90", "phoneNumber": "5343622375", "tenant": "beefull"}',
    status: 'limited',
    category: 'Dijital Hizmetler',
  },

  // ❌ ÇALIŞMAYAN SERVİSLER (Bot Koruması/DNS/Timeout)
  {
    id: 'migros',
    name: 'Migros',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Market',
  },
  {
    id: 'dominos',
    name: 'Dominos',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Yemek',
  },
  {
    id: 'starbucks',
    name: 'Starbucks',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Yemek',
  },
  {
    id: 'komagene',
    name: 'Komagene',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Yemek',
  },
  {
    id: 'kim_gb_ister',
    name: 'Kim GB İster',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'english_home',
    name: 'English Home',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'koton',
    name: 'Koton',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'joker',
    name: 'Joker',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'bim',
    name: 'Bim',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Market',
  },
  {
    id: 'penti',
    name: 'Penti',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'cineverse',
    name: 'Cineverse',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'naosstars',
    name: 'Naosstars',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'akasya_avm',
    name: 'Akasya AVM',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'AVM',
  },
  {
    id: 'akbati',
    name: 'Akbatı',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'AVM',
  },
  {
    id: 'yuffi',
    name: 'Yuffi',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Yemek',
  },
  {
    id: 'kuryem_gelsin',
    name: 'Kuryem Gelsin',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Kargo & Lojistik',
  },
  {
    id: 'marti',
    name: 'Martı',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Ulaşım',
  },
  {
    id: 'ido',
    name: 'İDO',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Ulaşım',
  },
  {
    id: 'hamidiye',
    name: 'Hamidiye',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Market',
  },
  {
    id: 'clickme_live',
    name: 'ClickMe Live',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'hizli_ecza',
    name: 'Hızlı Ecza',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Sağlık',
  },
  {
    id: 'paybol',
    name: 'Paybol',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Finans',
  },
  {
    id: 'tasdelen_su',
    name: 'Taşdelen Su',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Market',
  },
  {
    id: 'pidem',
    name: 'Pidem',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Yemek',
  },
  {
    id: 'orwi',
    name: 'Orwi',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'frink',
    name: 'Frink',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'tazi',
    name: 'Tazi',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'bisu',
    name: 'Bisu',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Ulaşım',
  },
  {
    id: 'bodrum_belediye',
    name: 'Bodrum Belediye',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Belediye',
  },
  {
    id: 'hey_scooter',
    name: 'Hey Scooter',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Ulaşım',
  },
  {
    id: 'tasimacim',
    name: 'Taşımacım',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Kargo & Lojistik',
  },
  {
    id: 'iste_gelsin',
    name: 'İste Gelsin',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Market',
  },
  {
    id: 'ipragaz',
    name: 'İpragaz',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Enerji',
  },
  {
    id: 'sancaktepe_belediye',
    name: 'Sancaktepe Belediye',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Belediye',
  },
  {
    id: 'bayrampasa_belediye',
    name: 'Bayrampaşa Belediye',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Belediye',
  },
  {
    id: 'macrocenter',
    name: 'Macrocenter',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Market',
  },
  {
    id: 'jimmy_key',
    name: 'Jimmy Key',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'alix_avien',
    name: 'Alix Avien',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Kozmetik',
  },
  {
    id: 'ayyildiz',
    name: 'Ayyıldız',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'tikla_gelsin',
    name: 'Tıkla Gelsin',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Yemek',
  },
  {
    id: 'kitapyurdu',
    name: 'Kitapyurdu',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Kitap & Medya',
  },
  {
    id: 'bkm_kitap',
    name: 'BKM Kitap',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Kitap & Medya',
  },
  {
    id: 'e_bebek',
    name: 'E-bebek',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Bebek & Çocuk',
  },
  {
    id: 'mothercare',
    name: 'Mothercare',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Bebek & Çocuk',
  },
  {
    id: 'toyzz_shop',
    name: 'Toyzz Shop',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Bebek & Çocuk',
  },
  {
    id: 'sportive',
    name: 'Sportive',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Spor',
  },
  {
    id: 'intersport',
    name: 'Intersport',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Spor',
  },
  {
    id: 'decathlon',
    name: 'Decathlon',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Spor',
  },
  {
    id: 'hm',
    name: 'H&M',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'zara',
    name: 'Zara',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'mango',
    name: 'Mango',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'bershka',
    name: 'Bershka',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'pull_bear',
    name: 'Pull&Bear',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'stradivarius',
    name: 'Stradivarius',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'massimo_dutti',
    name: 'Massimo Dutti',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'mediamarkt',
    name: 'Mediamarkt',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Teknoloji',
  },
  {
    id: 'teknosa',
    name: 'Teknosa',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Teknoloji',
  },
  {
    id: 'vatan_bilgisayar',
    name: 'Vatan Bilgisayar',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Teknoloji',
  },
  {
    id: 'itopya',
    name: 'İtopya',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Teknoloji',
  },
  {
    id: 'gamegaraj',
    name: 'GameGaraj',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Oyun',
  },
  {
    id: 'playstation',
    name: 'PlayStation',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Oyun',
  },
  {
    id: 'xbox',
    name: 'Xbox',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Oyun',
  },
  {
    id: 'nintendo',
    name: 'Nintendo',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Oyun',
  },
  {
    id: 'steam',
    name: 'Steam',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Oyun',
  },
  {
    id: 'epic_games',
    name: 'Epic Games',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Oyun',
  },
  {
    id: 'a101',
    name: 'A101',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Market',
  },
  {
    id: 'sok',
    name: 'Şok',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Market',
  },
  {
    id: 'carrefour',
    name: 'Carrefour',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Market',
  },
  {
    id: 'onur_market',
    name: 'Onur Market',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Market',
  },
  {
    id: 'happy_center',
    name: 'Happy Center',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Market',
  },
  {
    id: 'rossmann',
    name: 'Rossmann',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Kozmetik',
  },
  {
    id: 'watsons',
    name: 'Watsons',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Kozmetik',
  },
  {
    id: 'gratis',
    name: 'Gratis',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Kozmetik',
  },
  {
    id: 'flormar',
    name: 'Flormar',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Kozmetik',
  },
  {
    id: 'avon',
    name: 'Avon',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Kozmetik',
  },
  {
    id: 'oriflame',
    name: 'Oriflame',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Kozmetik',
  },
  {
    id: 'farmasi',
    name: 'Farmasi',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Kozmetik',
  },
  {
    id: 'lr',
    name: 'LR',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Kozmetik',
  },
  {
    id: 'herbalife',
    name: 'Herbalife',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Sağlık',
  },
  {
    id: 'amway',
    name: 'Amway',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Sağlık',
  },
  {
    id: 'forever_living',
    name: 'Forever Living',
    url: '',
    method: 'POST',
    payloadInfo: '',
    status: 'not_working',
    category: 'Sağlık',
  },
];

export const INITIAL_STATS = {
  totalSent: 0,
  success: 0,
  failed: 0,
  rateLimited: 0,
  sentOpaque: 0,
};
